//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovingObjects.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.GameObject = new HashSet<GameObject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PlayerId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual GameState GameState { get; set; }
        public virtual ICollection<GameObject> GameObject { get; set; }
    }
}
