//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovingObjects.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Highscore
    {
        public int PlayerId { get; set; }
        public string GameDifficulty { get; set; }
        public string GameSpeed { get; set; }
        public int Score { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
